---
title: "Lemur FPS analysis"
output: html_notebook
---


# Load libraries
```{r}
# Plotting
library(tidyverse)
library(ggtext)
library(cowplot)

# Stats
library(lme4)
library(lmerTest)

theme_set(theme_bw() +
            theme(axis.text = element_text(color = "black"),
                  axis.ticks = element_line(color = "black"),
                  plot.title = element_text(hjust = 0.5)))

set.seed(1234)



```

# Load data
```{r}
lemur_key <- read.csv("data/lemur_key.csv")

omit_aggregates <- function(df) {
  df[rowSums(df[,which(colnames(df) == "X2100"):which(colnames(df) == "X3500")]) == 0,] %>%
    return()
}

lemur_fps <- read.csv("data/lemurs.csv") %>%
  mutate(Sample.Name = gsub("lemurs.", "", Sample.Name) %>% as.numeric()) %>%
  left_join(lemur_key, by = c("Sample.Name" = "tube_no")) %>%
  relocate(name:common_name, .after = Sample.Name) %>%
  omit_aggregates()

summarize_fps_D <- function(df) {
  df %>%
    dplyr::select(Sample.Name:Dx..90.) %>%
    gather(key=D, value=val, (ncol(.)-2):ncol(.)) %>%
    mutate(D = case_when(D == "Dx..10." ~ "10th percentile",
                         D == "Dx..50." ~ "50th percentile (median)",
                         D == "Dx..90." ~ "90th percentile")) %>%
    group_by(Sample.Name, name, species, common_name, D) %>%
    dplyr::summarize(mean=mean(val), se=sd(val)/sqrt(length(val)))
}

summarize_fps_all_bins <- function(df) {
  df %>%
    gather(key=size, value=volume, (ncol(.)-100):ncol(.)) %>%
    mutate(size = as.numeric(substr(size, 2, nchar(size)))) %>%
    group_by(Sample.Name, name, species, common_name, size) %>%
    dplyr::summarize(mean=mean(volume)) %>%
    ungroup() %>%
    as.data.frame()
}

lemur_D <- summarize_fps_D(lemur_fps)
lemur_all_bins <- summarize_fps_all_bins(lemur_fps)

```

# Summarize medians and plot
```{r}
lemur_D50 <- lemur_D %>%
  dplyr::filter(D == "50th percentile (median)")

# Add mice (from Abx_and_GF_mice_fig.Rmd)
mouse_for_lemur <- data.frame(Sample.Name = NA, species = "Mus musculus", common_name = NA, D = NA,
                              mean = mouse_gf_D50 %>%
                                filter(Microbiome == "SPF") %>%
                                pull(median),
                              se = NA)

lemur_D50 <- rbind(lemur_D50, mouse_for_lemur) %>%
  mutate(species = factor(species, levels = rev(c("Lemur catta", "Propithecus coquereli", "Varecia variegata",
                                                  "Mus musculus"))))

lemur_D50_summary <- lemur_D50 %>%
  group_by(species, common_name) %>%
  summarize(mean2 = mean(mean), se = sd(mean)/sqrt(length(mean)))

fritz_summary <- data.frame(species = c("Lemur catta", "Propithecus coquereli", "Varecia variegata",
                                        "Mus musculus"),
                            mean2 = c(1913.7, NA, 2113.9, 208.5),
                            sd = c(624.8, NA, 833.5, 0),
                            n = c(3, NA, 4, 1)) %>%
  mutate(se = sd/sqrt(n))


lemur_D50_plot <- ggplot(lemur_D50, aes(x = mean, y = species)) +
  geom_point(position=position_jitter(width = 0, height = 0.05), alpha=0.25) +
  geom_errorbar(data = lemur_D50_summary, aes(y=species, xmin=mean2, xmax=mean2),
                color = "red", width=0.5, inherit.aes = F) +
  geom_errorbar(data = lemur_D50_summary, aes(y=species, xmin=mean2-se, xmax=mean2+se),
                width=0.25, inherit.aes = F) +
  geom_errorbar(data = fritz_summary, aes(y=species, xmin=mean2, xmax=mean2),
                color = "darkblue", width=0.5, inherit.aes = F) +
  geom_errorbar(data = fritz_summary, aes(y=species, xmin=mean2-se, xmax=mean2+se),
                color = "blue", width=0.25, inherit.aes = F) +
  labs(x = "Median FPS (μm)", y = "Species") +
  scale_x_log10()

```




